input:
  type: "dirs"
  location: ['.']
filter:
  extension: ['.pdf','txt']
pattern:
  sha1: "\\b[a-fA-F0-9]{40}\\b"
  sha256: "\\b[a-fA-F0-9]{64}\\b"
  md5: "\\b[a-fA-F0-9]{32}\\b"
  # domain: "(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}"
  # url: "(https?://)?([\\da-z\\.-]+)\\.([a-z\\.]{2,})([/\\w \\.-]*)*/?"
  ip_address: "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"
  email: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
output: 'output_pattern.csv'